// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env, loadEnvFile } from 'node:process';
import "dotenv/config";
import { defineConfig } from "prisma/config";

try {
  loadEnvFile(".env");
} catch (error) {
  if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") {
    throw error;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: env.DATABASE_URL || "",
  },
  migrations: {
    path: "prisma/migrations",
  },
});
